# Generated by Django 4.0.4 on 2022-11-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('replies', '0002_alter_reply_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='comment',
            new_name='comment_id',
        ),
    ]
